id: 8c2dfbb04f2c48239ed4a0e6dcb6e468
initial_creation_type: ocr
source_metadata:
  volumes:
    d14ecf5ee6244117a21f255acde73808:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: ''
      total_pages: 1586
      volume_number: 24
